// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nemo_network/listing/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Queries for the hard cap on listed markets
type QueryMarketsHardCap struct {
}

func (m *QueryMarketsHardCap) Reset()         { *m = QueryMarketsHardCap{} }
func (m *QueryMarketsHardCap) String() string { return proto.CompactTextString(m) }
func (*QueryMarketsHardCap) ProtoMessage()    {}
func (*QueryMarketsHardCap) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ef5aa4de5e6afc, []int{0}
}
func (m *QueryMarketsHardCap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMarketsHardCap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMarketsHardCap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMarketsHardCap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMarketsHardCap.Merge(m, src)
}
func (m *QueryMarketsHardCap) XXX_Size() int {
	return m.Size()
}
func (m *QueryMarketsHardCap) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMarketsHardCap.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMarketsHardCap proto.InternalMessageInfo

// Response type indicating the hard cap on listed markets
type QueryMarketsHardCapResponse struct {
	HardCap uint32 `protobuf:"varint,1,opt,name=hard_cap,json=hardCap,proto3" json:"hard_cap,omitempty"`
}

func (m *QueryMarketsHardCapResponse) Reset()         { *m = QueryMarketsHardCapResponse{} }
func (m *QueryMarketsHardCapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMarketsHardCapResponse) ProtoMessage()    {}
func (*QueryMarketsHardCapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ef5aa4de5e6afc, []int{1}
}
func (m *QueryMarketsHardCapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMarketsHardCapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMarketsHardCapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMarketsHardCapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMarketsHardCapResponse.Merge(m, src)
}
func (m *QueryMarketsHardCapResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMarketsHardCapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMarketsHardCapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMarketsHardCapResponse proto.InternalMessageInfo

func (m *QueryMarketsHardCapResponse) GetHardCap() uint32 {
	if m != nil {
		return m.HardCap
	}
	return 0
}

// Queries the listing vault deposit params
type QueryListingVaultDepositParams struct {
}

func (m *QueryListingVaultDepositParams) Reset()         { *m = QueryListingVaultDepositParams{} }
func (m *QueryListingVaultDepositParams) String() string { return proto.CompactTextString(m) }
func (*QueryListingVaultDepositParams) ProtoMessage()    {}
func (*QueryListingVaultDepositParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ef5aa4de5e6afc, []int{2}
}
func (m *QueryListingVaultDepositParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListingVaultDepositParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListingVaultDepositParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListingVaultDepositParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListingVaultDepositParams.Merge(m, src)
}
func (m *QueryListingVaultDepositParams) XXX_Size() int {
	return m.Size()
}
func (m *QueryListingVaultDepositParams) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListingVaultDepositParams.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListingVaultDepositParams proto.InternalMessageInfo

// Response type for QueryListingVaultDepositParams
type QueryListingVaultDepositParamsResponse struct {
	Params ListingVaultDepositParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryListingVaultDepositParamsResponse) Reset() {
	*m = QueryListingVaultDepositParamsResponse{}
}
func (m *QueryListingVaultDepositParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListingVaultDepositParamsResponse) ProtoMessage()    {}
func (*QueryListingVaultDepositParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5ef5aa4de5e6afc, []int{3}
}
func (m *QueryListingVaultDepositParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListingVaultDepositParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListingVaultDepositParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListingVaultDepositParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListingVaultDepositParamsResponse.Merge(m, src)
}
func (m *QueryListingVaultDepositParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListingVaultDepositParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListingVaultDepositParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListingVaultDepositParamsResponse proto.InternalMessageInfo

func (m *QueryListingVaultDepositParamsResponse) GetParams() ListingVaultDepositParams {
	if m != nil {
		return m.Params
	}
	return ListingVaultDepositParams{}
}

func init() {
	proto.RegisterType((*QueryMarketsHardCap)(nil), "nemo_network.listing.QueryMarketsHardCap")
	proto.RegisterType((*QueryMarketsHardCapResponse)(nil), "nemo_network.listing.QueryMarketsHardCapResponse")
	proto.RegisterType((*QueryListingVaultDepositParams)(nil), "nemo_network.listing.QueryListingVaultDepositParams")
	proto.RegisterType((*QueryListingVaultDepositParamsResponse)(nil), "nemo_network.listing.QueryListingVaultDepositParamsResponse")
}

func init() { proto.RegisterFile("nemo_network/listing/query.proto", fileDescriptor_d5ef5aa4de5e6afc) }

var fileDescriptor_d5ef5aa4de5e6afc = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc8, 0x4b, 0xcd, 0xcd,
	0x8f, 0xcf, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0xd6, 0xcf, 0xc9, 0x2c, 0x2e, 0xc9, 0xcc, 0x4b,
	0xd7, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x41, 0x56,
	0xa1, 0x07, 0x55, 0x21, 0x25, 0x92, 0x9e, 0x9f, 0x9e, 0x0f, 0x56, 0xa0, 0x0f, 0x62, 0x41, 0xd4,
	0x4a, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5,
	0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x65, 0x15, 0xb1, 0xda, 0x55, 0x90, 0x58,
	0x94, 0x98, 0x0b, 0x55, 0xa2, 0x24, 0xca, 0x25, 0x1c, 0x08, 0xb2, 0xdb, 0x37, 0xb1, 0x28, 0x3b,
	0xb5, 0xa4, 0xd8, 0x23, 0xb1, 0x28, 0xc5, 0x39, 0xb1, 0x40, 0xc9, 0x82, 0x4b, 0x1a, 0x8b, 0x70,
	0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x24, 0x17, 0x47, 0x46, 0x62, 0x51, 0x4a,
	0x7c, 0x72, 0x62, 0x81, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x7b, 0x06, 0x54, 0xa7, 0x02,
	0x97, 0x1c, 0x58, 0xa7, 0x0f, 0xc4, 0xb6, 0xb0, 0xc4, 0xd2, 0x9c, 0x12, 0x97, 0xd4, 0x82, 0xfc,
	0xe2, 0xcc, 0x92, 0x00, 0xb0, 0xc5, 0x4a, 0xe5, 0x5c, 0x6a, 0xf8, 0x55, 0xc0, 0xad, 0xf1, 0xe5,
	0x62, 0x83, 0x38, 0x16, 0x6c, 0x09, 0xb7, 0x91, 0xbe, 0x1e, 0xb6, 0xa0, 0xd1, 0xc3, 0x69, 0x90,
	0x13, 0xcb, 0x89, 0x7b, 0xf2, 0x0c, 0x41, 0x50, 0x43, 0x8c, 0xf6, 0x32, 0x71, 0xb1, 0x82, 0x6d,
	0x16, 0xca, 0xe3, 0xe2, 0x43, 0xf5, 0x99, 0x90, 0x26, 0x76, 0xa3, 0xb1, 0x04, 0x82, 0x94, 0x21,
	0xd1, 0x4a, 0xe1, 0x1e, 0x39, 0xcc, 0xc8, 0x25, 0x89, 0xd3, 0x95, 0x42, 0x26, 0x78, 0x0c, 0xc4,
	0xa9, 0x4b, 0xca, 0x86, 0x1c, 0x5d, 0x30, 0x17, 0x29, 0x19, 0x35, 0x5d, 0x7e, 0x32, 0x99, 0x49,
	0x47, 0x48, 0x4b, 0x1f, 0x6b, 0x1a, 0x29, 0x03, 0xe9, 0x8c, 0x4f, 0x81, 0x68, 0x8d, 0x87, 0x84,
	0x9f, 0x53, 0xf0, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38,
	0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x59, 0xa6, 0x67,
	0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0x82, 0xcd, 0xd3, 0x85, 0x99, 0x57, 0x66, 0xa2,
	0x9b, 0x9c, 0x91, 0x98, 0x99, 0xa7, 0x0f, 0x4e, 0x6d, 0xc9, 0xf9, 0x39, 0xfa, 0x15, 0x70, 0x3b,
	0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0x32, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x18, 0xe2, 0xa8, 0x87, 0x18, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries for the hard cap number of listed markets
	MarketsHardCap(ctx context.Context, in *QueryMarketsHardCap, opts ...grpc.CallOption) (*QueryMarketsHardCapResponse, error)
	// Queries the listing vault deposit params
	ListingVaultDepositParams(ctx context.Context, in *QueryListingVaultDepositParams, opts ...grpc.CallOption) (*QueryListingVaultDepositParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) MarketsHardCap(ctx context.Context, in *QueryMarketsHardCap, opts ...grpc.CallOption) (*QueryMarketsHardCapResponse, error) {
	out := new(QueryMarketsHardCapResponse)
	err := c.cc.Invoke(ctx, "/nemo_network.listing.Query/MarketsHardCap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListingVaultDepositParams(ctx context.Context, in *QueryListingVaultDepositParams, opts ...grpc.CallOption) (*QueryListingVaultDepositParamsResponse, error) {
	out := new(QueryListingVaultDepositParamsResponse)
	err := c.cc.Invoke(ctx, "/nemo_network.listing.Query/ListingVaultDepositParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries for the hard cap number of listed markets
	MarketsHardCap(context.Context, *QueryMarketsHardCap) (*QueryMarketsHardCapResponse, error)
	// Queries the listing vault deposit params
	ListingVaultDepositParams(context.Context, *QueryListingVaultDepositParams) (*QueryListingVaultDepositParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) MarketsHardCap(ctx context.Context, req *QueryMarketsHardCap) (*QueryMarketsHardCapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarketsHardCap not implemented")
}
func (*UnimplementedQueryServer) ListingVaultDepositParams(ctx context.Context, req *QueryListingVaultDepositParams) (*QueryListingVaultDepositParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListingVaultDepositParams not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_MarketsHardCap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMarketsHardCap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MarketsHardCap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nemo_network.listing.Query/MarketsHardCap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MarketsHardCap(ctx, req.(*QueryMarketsHardCap))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListingVaultDepositParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListingVaultDepositParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListingVaultDepositParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nemo_network.listing.Query/ListingVaultDepositParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListingVaultDepositParams(ctx, req.(*QueryListingVaultDepositParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nemo_network.listing.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MarketsHardCap",
			Handler:    _Query_MarketsHardCap_Handler,
		},
		{
			MethodName: "ListingVaultDepositParams",
			Handler:    _Query_ListingVaultDepositParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nemo_network/listing/query.proto",
}

func (m *QueryMarketsHardCap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMarketsHardCap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMarketsHardCap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryMarketsHardCapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMarketsHardCapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMarketsHardCapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HardCap != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.HardCap))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryListingVaultDepositParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListingVaultDepositParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListingVaultDepositParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryListingVaultDepositParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListingVaultDepositParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListingVaultDepositParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryMarketsHardCap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryMarketsHardCapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HardCap != 0 {
		n += 1 + sovQuery(uint64(m.HardCap))
	}
	return n
}

func (m *QueryListingVaultDepositParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryListingVaultDepositParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryMarketsHardCap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMarketsHardCap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMarketsHardCap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMarketsHardCapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMarketsHardCapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMarketsHardCapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HardCap", wireType)
			}
			m.HardCap = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HardCap |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListingVaultDepositParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListingVaultDepositParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListingVaultDepositParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListingVaultDepositParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListingVaultDepositParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListingVaultDepositParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
